remove version buildx setup
Due to concurrency limit error
ERROR: failed to build: failed to solve: build cannot proceed concurrent build limit of 0 reached